# This must always remain the same for the Windows installer infrastructure
# to know which program to upgrade.
UPGRADE_GUID = c21a52f7-03f8-da11-953c-000f1f7a3a99

include ../salma-hayek/simple.make
