#!/bin/bash
tools_dir=`dirname $0`
tool_name=$1

class_path=$tools_dir/classes:$tools_dir/../salma-hayek/classes
class_path=$class_path:$tools_dir/scm.jar

shift
if [ "`uname`" == "Darwin" ]
then
    os_specific_options=-Xdock:name=$tool_name
fi

exec java $os_specific_options -cp $class_path e.scm.$tool_name "$@"
