.TH SCM "1" "" "jessies.org" "User Commands"
.SH NAME
checkintool \- check changes into source code control
.SH SYNOPSIS
.SY checkintool
.YS
.SH DESCRIPTION
.B checkintool
is used to check changes into source code control. It replaces
.BR "bzr commit" ,
.BR "cvs commit" ,
.BR "git commit" ,
.BR "hg commit" ,
.BR "svn commit" ,
or
.BR "bk citool" .

.SH "SEE ALSO"
.BR revisiontool (1).

More documentation is available on our
.UR https://github.com/software-jessies-org/jessies/wiki/SCM
github wiki
.UE
.SH "REPORTING BUGS"
Report bugs to <evergreen-users@googlegroups.com>.
