.TH SCM "1" "" "jessies.org" "User Commands"
.SH NAME
revisiontool \- examine a file's source code control history
.SH SYNOPSIS
.SY revisiontool
.I FILE\fR[:\fILINE\fR]]
.YS
.SH DESCRIPTION
.B revisiontool
is used to examine a file's history in source code control. It's a local
alternative to
.I cvsweb
and its relatives, similar to
.BR "bk revtool" .

.SH "SEE ALSO"
.BR checkintool (1),
.BR gitk (1).

More documentation is available on our
.UR https://github.com/software-jessies-org/jessies/wiki/SCM
github wiki
.UE
.SH "REPORTING BUGS"
Report bugs to <evergreen-users@googlegroups.com>.
